### ISSUE TITLE
[BUG] Wrong alpha tiles using "mm_pause_screen.ppf"

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#86] opened 2023-09-26 22:33 UTC
**Description**
In the event you have less important issues to deal with, **"mm_pause_screen.ppf"** have the texture : 

**_THE LEGEND OF ZELDA#16C424D0#3#1_all_** or **_"16C424D0"_**, is corrupted with a black rectangle when patched.

But no hurry. It's more of a bothering thing than a truly broken one, and in the context of **PPF** files, they can only be created/edited by its original creator. So, there.

**Comment by GoldenMariaNova** [comment] 2023-09-27 01:24
> snips

I do hope Glide64 extract the exact names of textures, otherwise it's useless.

**Comment by Admentus64** [comment] 2023-09-27 07:11
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/c5a036d3-37b2-43fa-874d-ed846cc01496)
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/286bad74-b8b7-4f24-a9c1-f30e0dda8407)

I don't see what's broken about it? You mean the Character Equipment preview screen? I don't see what the issue is? Closing it.

Please show me with a screenshot what is broken about this option and I re-open it.

**Comment by Admentus64** [comment] 2023-09-27 07:12
Oh never mind. I just noticed it. Yeah... Item Select upper right corner.

**Comment by Admentus64** [comment] 2023-09-27 07:17
The dump is also wrong you posted. It's supposed to be 80x32. And it's multiple textures that need a re-inject.

Sadly I am not going to work on this. It's not my department, and patch in the first place. Closing it again.

Someone else is always free to fix it and submit a PR.

**Comment by GhostlyDark** [comment] 2023-09-27 17:05
Thanks for reporting. Fixed via 43fd790c902a0a69f872f07b66e16696a59c026b.

**Closed by GhostlyDark** 2023-09-27 17:05 UTC
Labels: bug

**Comment by GoldenMariaNova** [comment] 2023-09-27 17:43
> Thanks for reporting. Fixed via [43fd790](https://github.com/Admentus64/Patcher64Plus-Tool/commit/43fd790c902a0a69f872f07b66e16696a59c026b).

Thank you.

**Comment by Admentus64** [comment] 2023-09-28 18:12
Please turn this into it's oen issue report.

**Comment by GoldenMariaNova** [comment] 2023-09-28 18:57
> Please turn this into it's own issue report.

Wouldn't that be spam?

Well, I did it anyways. I hope it's resolved for good, it's ridiculous.
