### ISSUE TITLE
[BUG] Patcher64+ : Missing Shield Textures Options (OOT) and Dampé Unpatched Censored Gerudo Texture

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#76] opened 2023-07-20 18:38 UTC
It seems that **"Skilar's OoT Shield"** and **"Skilar's TP Shield"**, are missing from the **Hylian Shield** options in the **Patcher64+** Equipment tab for **OOT**.

Also, when you have completed dampé race, the end room decorations at the top are still the uncensored crescent moon, while the decorations at the beginning of the same cave **ARE** patched, when you choose the **"Censored Gerudo Textures"** option. 

On the same note, MM Adult Link should have his shield texture updated with the **"Skilar's OoT Shield"**, at it seems to be more recent, but if you can't do that, I understand.

**Comment by Admentus64** [comment] 2023-07-20 19:33
1. Not a bug. It's simply not available.

2. Censored Gerudo Textures is already reworked. Dampé Cave is a bit special. The censored texture isn't missing there. It was only changed on the Wii VC version through T64 injects. So there's nothing to replace if it was never in the ROM.

3. Not a bug either. If it's the HD texture, wrong report. If it's the model, wrong repo. Report any model issues to the author of the model itself.

Closing this bug report. None of the bug reports are viable. Also make sure to limit it to one issue per bug report.

**Closed by Admentus64** 2023-07-20 19:33 UTC
Labels: bug

**Comment by GhostlyDark** [comment] 2023-07-20 19:40
Dampé's Grave never received the new symbol, not even on Wii VC iirc. The symbol was simply removed. So while we could inject that texture, it would only remove the symbol - not replace it.

**Comment by GoldenMariaNova** [comment] 2023-07-20 20:30
> 1. Not a bug. It's simply not available.
> 2. Dampé Cave is a bit special. The censored texture isn't missing there. It was only changed on the Wii VC version through T64 injects, but this only removes the symbol and doesn't not replace it with a censored version. So there's nothing to replace if it was never in the ROM.
> 3. Not a bug either. The patcher works with SD textures only, so this isn't the place to report inaccurate HD textures. If it's an issue with the model then you're in the wrong place too, as you should report any model issues to the author of the model itself instead. The model hasn't been changed and is used as it was made by the original author.
> 
> Closing this bug report. There's nothing to fix. Make sure to limit it to one issue per bug report.

I am so sorry to have bothered you with this useless report.

Also for the third point, I wanted to prevent spam-posting *"bugs"* reports, but ok.

Sorry again.

**Comment by GoldenMariaNova** [comment] 2023-07-20 20:32
> Dampé's Grave never received the new symbol, not even on Wii VC iirc. The symbol was simply removed. So while we could inject that texture, it would only remove the symbol - not replace it.

Seems the best thing to do here.

**Comment by Admentus64** [comment] 2023-07-20 20:37
If it was a ROM textures yes. But alas, it's a T64 inject.

**Comment by GoldenMariaNova** [comment] 2023-07-20 20:38
> If it was a ROM texture yes. But alas, it's a T64 inject.

Well, crap.
