### ISSUE TITLE
[BUG]When choosing Brazilian Portuguese in Majora's Mask, the game does not start after choosing the profile.

### ISSUE THREAD

**Issue by MINUS535** [Admentus64/Patcher64Plus-Tool#81] opened 2023-09-14 21:01 UTC
After choosing Brazilian Portuguese in Majora's Mask, the game does not start after choosing the profile, the game simply freezes.

**Comment by Admentus64** [comment] 2023-09-15 06:52
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/61ef0908-704d-4c29-bd63-2606edd9bd1a)

Seems to work fine. Issue couldn't be verified. Closing this issue therefore.

Please provide more specific settings on how to reproduce this issue and I re-open it again.

**Comment by MINUS535** [comment] 2023-09-15 12:51
Sorry, I'll send more information now.

When using the tool, I select only the mentioned language and the following option.
![02](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/a72ffde5-d342-400e-9597-105971ef8335)

After everything is applied, I try to start a new game, but the screen freezes. I use both mupen64plus through Retroarch and project64, both with their default options. 

![05](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/3e97fec6-4c1d-4ad4-8286-28ac027069b1)
![06](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/d72221f0-39b3-4c24-b177-33b2103ed848)
![07](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/6f46bae4-7227-4db2-a61f-288617157192)
![08](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/f38861f0-f920-475a-9d56-3f873a19ab2b)

The same does not happen if I select any other language, like French in these examples

![09](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/67aef3de-fee4-4eb9-81f2-90c0d11af46d)

![10](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145051024/2b9f39d1-e8eb-419a-b35c-0fbd3bd63262)

Again, sorry for the lack of information. English is not my native language and I am always afraid of writing something wrong. Thank you very much for the tool and for everything you did for the community.

**Comment by Admentus64** [comment] 2023-09-15 13:46
Default options right?

I use that too in the screenshot I posted (with Brazilian). You also didn't specify the patcher version you used, so I am going to assume the newest master build was used which is 21.0.3 hotfix 1.

In which case there is no error, since it should work fine. I am still going to need more specific information what used.

I patched it again using absolute default settings except for changing the language, and it still booted fine on my end. So I am not sure what could be wrong here.

Please double check with your respective emulator forum that the emulator settings, versions and plugins are correct and up to date.

**Comment by GhostlyDark** [comment] 2023-09-15 14:40
Reproducible on my end. Investigating now.

**Comment by Admentus64** [comment] 2023-09-15 14:40
Confirmed. I was able to replicate it. The trick was to disable Redux with compression enabled.

**Comment by GhostlyDark** [comment] 2023-09-15 15:01
Fixed via df79035b9f5106cbfe2aae618423edd3da362a58. Updating the Patcher should do the trick.

**Closed by GhostlyDark** 2023-09-15 15:01 UTC
Labels: bug

**Comment by MINUS535** [comment] 2023-09-15 17:48
Apparently everything is working fine here. Thank you so much for everything.
