### ISSUE TITLE
Majora's Mask not Downgrading properly

### ISSUE THREAD

**Issue by MoriyaFaith** [Admentus64/Patcher64Plus-Tool#13] opened 2021-02-06 23:00 UTC
I'm trying to downgrade my GC MM rom, and it's not completely downgrading properly. The checksum is wrong, and Patcher 64+ doesn't recognize it as a valid MM rom. This is the checksum I get back when I try to get a look at it.
![image](https://user-images.githubusercontent.com/46070717/107131509-1ec43600-68a5-11eb-9dbc-a4ca2864259e.png)

**Comment by Admentus64** [comment] 2021-02-06 23:02
Are you sure there aren't any option or patches patched in? You can enable the console log to confirm what is getting patched in.

**Comment by MoriyaFaith** [comment] 2021-02-06 23:04
It doesn't allow me to turn on the console.
![image](https://user-images.githubusercontent.com/46070717/107131582-c2ade180-68a5-11eb-9f1c-169b9916706f.png)

**Comment by Admentus64** [comment] 2021-02-06 23:04
The console log can not be used when running the .exe. It's script only.

**Comment by Admentus64** [comment] 2021-02-06 23:06
I see do indeed notice a proper Rev0 hash is not generated. The tool was never meant for a true downgrade to Rev0. It's still Rev0, but minor changes like the header cause a different hashsum. This is still enough for purposes to customize the ROM. ROMs have to be downgraded to Rev0 in order to be patched.

**Comment by MoriyaFaith** [comment] 2021-02-06 23:12
I see. I was just confused since this issue doesn't appear when downgrading OOT, so I was wondering if there was a reason for this.

**Comment by Admentus64** [comment] 2021-02-06 23:13
The finalize_rev0.bps patch was meant to result into an identical rev0 ROM. That at least worked for OoT. I give it a look for MM and see if something went differently there. I come back on it, if I discover the error.

**Comment by MoriyaFaith** [comment] 2021-02-07 01:26
Got it.

**Comment by Admentus64** [comment] 2021-02-07 08:04
Ok. The issue is going to be solved for the next update. The problem was with the DMA Table for the decompressed ROM which still used that one meant for Redux (which is based on Rev0) rather than an untouched Rev0. OoT didn't have this issue since it's Redux patch shared the same DMA Table as with the untouched Rev0 ROM.

To address this, both the Games.json and Patches.json (for MM) files got updated with new DMA Tables, and a few code changes so that the new specifications for Patches.json can be read.

I leave this issue open until release of the next update.

**Comment by Admentus64** [comment] 2021-02-10 13:57
Hopefully fixed with v11.3.0.

**Closed by Admentus64** 2021-02-10 13:57 UTC
