### ISSUE TITLE
[BUG] (Virtual Console) Breaking Grass Crashes Majora's Mask + Game Not Showing in Wii Menu

### ISSUE THREAD

**Issue by AleNinten** [Admentus64/Patcher64Plus-Tool#137] opened 2024-02-18 23:16 UTC
**Description**
Upon breaking grass with Link, there is a chance the game crashes right after. Furthermore, the game does not show in the Wii Menu once you install it, and shows as a big question mark in the Channels option of Wii's Data Management (Screenshot via Dolphin has been attached, it however acts the same on original hardware, tested).

**This is very worth noting,** but due to how the game is unabled to be accessed from the menu, it has been accessed through the homebrew loader, PostLoader, as you can boot channels from there and the game is detected. The game's booted from a 4.3U emuNAND, since my real NAND is 4.3E and the game has audio issues as a result, like any other american VC title.

**How to Reproduce**
For the crash: break grass with Link, it will be ensured to crash after after some attempts.
For the menu issue: Just install the MM WAD. It will be not shown, and appear as a question mark slot on the data management. Accessible by other means.

**Expected behavior**
For the crash: for the crash to not happen, and be able to keep playing as usual.
For the menu issue: for the game to appear on it, and be accessible via the Wii Menu like any other channel.

**Log files**
[2024-02-16.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/14324821/2024-02-16.log)

**Screenshots**

![0000000100000002_2024-02-19_00-06-09](https://github.com/Admentus64/Patcher64Plus-Tool/assets/85452907/fbda988c-2061-405a-9e2a-3b8ddab3cb37)

**Comment by Admentus64** [comment] 2024-02-18 23:30
Disable channel changes. Wii doesn't like it. It's meant for Dolphin.

**Comment by AleNinten** [comment] 2024-02-18 23:35
> Disable channel changes. Wii doesn't like it. It's meant for Dolphin.
> 
> As for the crash issue. I need specifics. Can't fix it otherwise.

Understood about the first one, will do for a next patch.

As of the crash specifics, I'm not sure how much clearer can I get. Whenever link breaks grass patches with his sword, the whole game halts and I have to power off the wii by holding the power button. If there's anything I can do that can get a clearer picture let me know.

**Comment by AleNinten** [comment] 2024-02-18 23:45
Seriously, I just wanna help you here to report an issue. I do not know how can I be more specific than "doing this makes the game break", I do not know how being as clear as water marks it as "incomplete" when I cannot give any other details further than that. I already told everything I did, both to load the game, and make it break. There's nothing more I can say man.

**Comment by Admentus64** [comment] 2024-02-18 23:48
Relax dude. I wasn't being offensive.

Closing this issue due not not willing to cooperate and taking the issue seriously.

**Comment by AleNinten** [comment] 2024-02-18 23:49
My apologies for coming in as rude as I got, wasn't my intention. I just wanna help, I promise.

**Comment by Admentus64** [comment] 2024-02-19 08:17
Alright. I reopen the issue again.

Like I was saying I am going to need more specifics in order for me to locate the cause and replicate the issue so it can be fixed.

Right now it looks like the issue is a bunch of options which may cause a crash randomly after cutting grass. This has to be narrowed down as much as it can in a way I can easily test this myself.

Examples on information that are useful:
- Exact step by step on what happens booting up the console (ex. which area, interactions and so on). Use the minimal amount of required steps. The fewer steps you need to occur the crash the better. Making it crash on a fresh debug save slot is even better (provided it crashes on regular save slots too).
- The least amount of options patched in by Patcher64+. The fewer the better. Any option which has no effect on the crash should be left disabled. In order to speed up testing which options you can disable, use the Divide and Conquer approach.

Divide and Conquer:
1. Disable half of the options you had enabled.
2. Test the issue and see if it occurs.
2a. If it occurs, go back and enable half of what you just had disabled. Repeat this step again again.
2b. If it doesn't occur, repeat steps 1 and 2 again.
3. Eventually you should be able to narrow down which specific option can cause the crash.
For most options common sense could be applied to determine if they have an effect on the crashing. Such as colors. Then again, you might never know. Redux itself could be the cause too.

**Comment by Admentus64** [comment] 2024-02-25 09:30
Closing and locking this issue due to lack of interest.

**Closed by Admentus64** 2024-02-25 09:30 UTC
Labels: invalid, incomplete
