### ISSUE TITLE
When making an OOT Rev 0 rom changing the heart values instantly crashes the launcher and deletes the files

### ISSUE THREAD

**Issue by FrenzeFanAccount** [Admentus64/Patcher64Plus-Tool#38] opened 2022-05-20 03:55 UTC
In the starting items section the health has a value of 20, when trying to change this the launcher crashes and deletes its exe

**Comment by Admentus64** [comment] 2022-05-20 06:50
While I can understand there could be an issue with some options, but flat out crashing and then deleting it's .exe file should be impossible. First off all, it's a PowerShell script and not an executable. The .exe is just a launcher. You could still run the script without the .exe. Second of all and most important, there should be no code whatsoever in the script that wants to remove files from the root folder.

Deleting files are strictly limited to the game folders of the patcher which contain extracted assets or the temp folder which is in used during patching.

It is correct that this health option had a default starting value of 20 on every bootup (and that's the only issue it had, no crashing or deleting files when you change it, in fact changing that value never gave any issues), but which has since been fixed on the latest master version.

I am not sure if I should close this issue or not. Not saying you're making this up, but like I said it seems almost impossible for this to specifically occur. It's definitely not something I can replicate myself, meaning it can't be fixed (because the issue doesn't exist in the first place to begin with).

It almost seems to me something else is wrong on your system instead. PowerShell is script-language part which comes integrated with Windows 10/11, and has to be installed on Windows 7/8/8.1. It's far more likely to theorize something is likely wrong with your Windows OS instead.

For now, there's nothing I can do. There's simply far too much info lacking in your bug report. No log file is included. No images. No system specs. Basicially nothing I can use to determine what could be going wrong.

Please follow up with as much detailed info as you possibly can. Otherwise this issue has to be considered to be closed. I'm removing the [bug] tag until it's confirmed to be a bug.

**Comment by GhostlyDark** [comment] 2022-05-28 19:04
Cannot reproduce.

**Closed by GhostlyDark** 2022-05-28 19:04 UTC
