### ISSUE TITLE
[BUG] [MM] Black screen after doggie racetrack

### ISSUE THREAD

**Issue by ngmoviedo** [Admentus64/Patcher64Plus-Tool#90] opened 2023-10-02 17:19 UTC
**Description**
On Majora's Mask, after playing the doggie racetrack minigame, the screen turns to black, independently of the result of the race.
Occasionaly, a red bar can be observed such as in issue #89.

**How to Reproduce**
1. Patch Majora's Mask with Patcher64Plus version 22.0.0 - Hotfix 12.
   - Reset Options
   - Quality of Life + Uncensor & Correct + Improved Link
2. Play the ROM with Project 64, using [Rosalie's Better Majora's Mask Installer cofiguration](https://github.com/Rosalie241/BetterMajorasMaskInstaller)

**Expected behavior**
Game should continue.

**Screenshots**
See #89.

**Log files**.
[2023-10-02.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/12784892/2023-10-02.log)

**Comment by Admentus64** [comment] 2023-10-02 17:26
I look into it.

**Comment by ngmoviedo** [comment] 2023-10-02 17:49
Not sure if this is related or not... It may have to do with the save states I've made in order to test this bug, but the game seems to be unable to save by in-game means now. Could the bug have caused some kind of save corruption? I haven't deleted any saves, but the game seems unable to read them. I'll look into that and report any findings-

**Comment by Admentus64** [comment] 2023-10-02 17:50
Please don't use save states. Please confirm again without or the issue will be closed.

**Comment by ngmoviedo** [comment] 2023-10-02 17:53
No, don't worry. The issue occurred with regular saves. I just used save states to easily get to the point where the bug occurred again. But the first couple of times I got it I got there the intended way.

**Comment by Admentus64** [comment] 2023-10-02 17:57
As long the bug is confirmed without involving save states I look into it.

Save states are known for causing issues.

**Comment by Admentus64** [comment] 2023-10-02 20:50
Seems legit. The issue is the Restore Text option. I suggest disabling that option.

**Comment by ngmoviedo** [comment] 2023-10-03 18:07
Can confirm it works correctly with that option disabled.

**Comment by Admentus64** [comment] 2023-10-07 22:34
Hopefully fixed with v22.0.3.

**Closed by Admentus64** 2023-10-07 22:34 UTC
Labels: bug
